### ISSUE TITLE
[1.0.3] Server crashes when taking photo in non-overworld dimensions

### ISSUE THREAD

**Issue by QBFreak** [ProfMobius/Modjam5#5]
If I take a photo in a dimension other than the Overworld (such as the Nether, or a dimension from Mystcraft) the server crashes with

```Description: Exception in server tick loop```

I am using the Polaroid camera.
I am running Forge `forge-1.12.2-14.23.4.2705`
My list of mods is a bit long, it's probably best seen in the crash report.

The crash report is attached.

[crash-2018-07-10_17.27.12-server.txt](https://github.com/ProfMobius/Modjam5/files/2182249/crash-2018-07-10_17.27.12-server.txt)

Please let me know if you need further testing to narrow this down.

**Comment by QBFreak** [comment]
If I had been paying attention to the server output, I would have seen this `Photographer player is null, which means we can't produce an item. Sorry :(`

I decided to dust off my weak modding skills (ok, so I did a tutorial once), and actually managed to come up  with what I believe is a reasonable fix (that is to say, I Googled it :) ). Take a look at QBFreak/Modjam5@4036e35 and see if it looks satisfactory. I tested it both in the Overworld and the Nether. I'll send along a Pull Request so you can implement it if you desire.

**Comment by ItsAnysek** [comment]
> 
> 
> If I had been paying attention to the server output, I would have seen this `Photographer player is null, which means we can't produce an item. Sorry :(`
> 
> I decided to dust off my weak modding skills (ok, so I did a tutorial once), and actually managed to come up with what I believe is a reasonable fix (that is to say, I Googled it :) ). Take a look at [QBFreak/Modjam5@4036e35](https://github.com/QBFreak/Modjam5/commit/4036e35) and see if it looks satisfactory. I tested it both in the Overworld and the Nether. I'll send along a Pull Request so you can implement it if you desire.

Hey QBFreak, I tested your code. However, when I try to load a world, I get this error.

https://www.dropbox.com/s/jx2b5t15092kpa0/crash-2019-07-20_20.38.25-server.txt?dl=0

**Comment by QBFreak** [comment]
Hmm. I just rebuilt it from my repo and it seemed to work just fine. 

- What version of Forge did you use when you compiled it?
- Are you building with gradle, Eclipse, IDEA?
- Is PTRLib included in your dependencies?
  - (The `build.gradle` in the repo includes it, but if you didn't use that, or didn't use gradle to create the project for your IDE and are building from the IDE, you probably don't have it)

My guess is PTRLib is missing, but that's a guess. If not, can you answer the following?

- What version of Forge are you using when you try to run it?
- What version of Minecraft are you using? (1.12, 1.12.2?)
- What version of PTRlib are you using?
- When does the crash occur? As soon as you try to open a world?
- Have you successfully opened the world before with the mod installed?

**Comment by QBFreak** [comment]
@ItsAnysek Here's the build I was testing with: https://github.com/QBFreak/Modjam5/releases/tag/v1.0.5

**Comment by DoomRater** [comment]
I hate to mention things not related to the main project, but I'm unable to report issues on QBFreak's build.  After updating to your 1.0.5 build, all picture frames are tiny.  They used to be quite large, but I can't see anything that has changed between your build and this one to cause a size change.

**Comment by QBFreak** [comment]
Whoops. Apparently issues can be disabled, and are by default on forked repos. Fixed that.

I also didn't realize that the release on CurseForge is 1.0.3 while I forked and modified 1.0.4. At some point in the middle the hanging frame size was changed. As a stop-gap, I've uploaded a new release, 1.0.3a, that I believe is the same as the release on CurseForge, with the addition of my patch for multi-dimension use.

You can find it here: https://github.com/QBFreak/Modjam5/releases/tag/v1.0.3a
